# Redisson 配置文件（分布式锁）
singleServerConfig:
  # Redis 地址
  address: "redis://localhost:6379"
  
  # 连接超时（毫秒）- 建立连接最多等待时间
  connectTimeout: 10000
  
  # 命令超时（毫秒）- 执行命令最多等待时间
  timeout: 3000
  
  # 数据库索引（0-15）
  database: 0
  
  # 连接池大小（单机建议 10-20）
  connectionPoolSize: 15
  
  # 最小空闲连接
  connectionMinimumIdleSize: 7
  
  # 空闲连接超时（毫秒）
  idleConnectionTimeout: 10000
  
  # 重试次数
  retryAttempts: 3
  
  # 重试间隔（毫秒）
  retryInterval: 1500